export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_SELECTED_MOVIE = 'FETCH_SELECTED_MOVIE';
export const FETCH_SELECTED_MOVIE_CREDITS = 'FETCH_SELECTED_MOVIE_CREDITS';
export const FETCH_SELECTED_MOVIE_REVIEW = 'FETCH_SELECTED_MOVIE_REVIEW';

export const ERROR_MSG = 'ERROR_MSG';
export const TRENDING_MOVIES = 'TRENDING_MOVIES';
export const UPCOMING_MOVIES = 'UPCOMING_MOVIES';
export const MOVIE_ID = 'MOVIE_ID';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const CREATE_MOVIE_RATE = 'CREATE_MOVIE_RATE';
export const UPDATE_MOVIE_RATE = 'UPDATE_MOVIE_RATE';
export const DELETE_MOVIE_RATE = 'DELETE_MOVIE_RATE';
export const GET_MOVIE_RATE = 'GET_MOVIE_RATE';
export const GET_MOVIES_RATES = 'GET_MOVIES_RATES';

export const CREATE_MOVIE_REVIEW = 'CREATE_MOVIE_REVIEW';
export const UPDATE_MOVIE_REVIEW = 'UPDATE_MOVIE_REVIEW';
export const DELETE_MOVIE_REVIEW = 'DELETE_MOVIE_REVIEW';
export const GET_MOVIE_REVIEW = 'GET_MOVIE_REVIEW';
export const GET_MOVIE_REVIEWS = 'GET_MOVIE_REVIEWS';

export const ADD_TO_WATCHLIST = 'CREATE_WATCHLIST';
export const DELETE_FROM_WATCHLIST = 'UPDATE_WATCHLIST';
export const WATCHLIST_CHECK = 'WATCHLIST_CHECK';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// export const ICON_CLICK = "ICON_CLICK";
